const LOAD_INGREDIENTS_REQUEST = "LOAD_INGREDIENTS_REQUEST";
const LOAD_INGREDIENTS_SUCCESS = "LOAD_INGREDIENTS_SUCCESS";
const LOAD_INGREDIENTS_ERROR = "LOAD_INGREDIENTS_ERROR";
const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";
const SET_CONSTRUCTOR_INGREDIENTS = "SET_CONSTRUCTOR_INGREDIENTS";
const UPDATE_CONSTRUCTOR_INGREDIENTS = "UPDATE_CONSTRUCTOR_INGREDIENTS";
const DEL_CONSTRUCTOR_INGREDIENTS = "DEL_CONSTRUCTOR_INGREDIENTS";
const SET_CONSTRUCTOR_BUN = "SET_CONSTRUCTOR_BUN";
const SET_CONSTRUCTOR_PRICE = "SET_CONSTRUCTOR_PRICE";
const SET_ORDER_NUMBER = "SET_ORDER";
const DEL_CURRENT_INGREDIENT = "DEL_CURRENT_INGREDIENT";

export {
  LOAD_INGREDIENTS_REQUEST,
  LOAD_INGREDIENTS_SUCCESS,
  LOAD_INGREDIENTS_ERROR,
  UPDATE_INGREDIENTS,
  SET_CURRENT_INGREDIENT,
  UPDATE_CONSTRUCTOR_INGREDIENTS,
  SET_CONSTRUCTOR_INGREDIENTS,
  DEL_CONSTRUCTOR_INGREDIENTS,
  SET_CONSTRUCTOR_BUN,
  SET_CONSTRUCTOR_PRICE,
  SET_ORDER_NUMBER,
  DEL_CURRENT_INGREDIENT
};
