const LOAD_INGREDIENTS = "LOAD_INGREDIENTS";
const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";
const SET_CONSTRUCTOR_INGREDIENTS = "SET_CONSTRUCTOR_INGREDIENTS";
const UPDATE_CONSTRUCTOR_INGREDIENTS = "UPDATE_CONSTRUCTOR_INGREDIENTS";
const DEL_CONSTRUCTOR_INGREDIENTS = "DEL_CONSTRUCTOR_INGREDIENTS";
const SET_CONSTRUCTOR_BUN = "SET_CONSTRUCTOR_BUN";
const SET_CONSTRUCTOR_PRICE = "SET_CONSTRUCTOR_PRICE";
const SET_ORDER = "SET_ORDER";

export {LOAD_INGREDIENTS, SET_CURRENT_INGREDIENT, UPDATE_CONSTRUCTOR_INGREDIENTS, SET_CONSTRUCTOR_INGREDIENTS, DEL_CONSTRUCTOR_INGREDIENTS, SET_CONSTRUCTOR_BUN, SET_CONSTRUCTOR_PRICE, SET_ORDER}