const USER_LOGIN = "USER_LOGIN";
const USER_REGISTER = "USER_REGISTER";
const USER_LOGOUT = "USER_LOGOUT";
const USER_TOKEN = "USER_TOKEN";
const GET_USER = "GET_USER";
const PATCH_USER = "PATCH_USER";

export {
  USER_LOGIN,
  USER_REGISTER,
  USER_LOGOUT,
  USER_TOKEN,
  GET_USER,
  PATCH_USER
};
